default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo-api-ontrails_development

test:
  <<: *default
  database: todo-api-ontrails_test

production:
  <<: *default
  database: todo-api-ontrails_production
  username: todo-api-ontrails
  password: <%= ENV['TODO-API-ONTRAILS_DATABASE_PASSWORD'] %>
